apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-identity-provider
  namespace: sandbox-system
  labels:
    component: agent-identity-provider
    app.kubernetes.io/name: agent-identity-provider
    app.kubernetes.io/managed-by: kustomize
automountServiceAccountToken: true
